/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
 
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  PoseidonT4,
  PoseidonT4Interface,
} from "../../../../contracts/logic/Poseidon.sol/PoseidonT4";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[3]",
        name: "input",
        type: "bytes32[3]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61012561003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80635a53025d146038575b600080fd5b60496043366004605b565b50600090565b60405190815260200160405180910390f35b600060608284031215606c57600080fd5b82601f830112607a57600080fd5b6040516060810181811067ffffffffffffffff82111715609a57609a60d9565b60405280836060810186101560ae57600080fd5b60005b600381101560ce57813583526020928301929091019060010160b1565b509195945050505050565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220410b5fb873b4c3a57f27d85ae6cfdc1e0f334a0d7ecf76a3605f0a593d08af0c64736f6c63430008070033";

type PoseidonT4ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PoseidonT4ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PoseidonT4__factory extends ContractFactory {
  constructor(...args: PoseidonT4ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PoseidonT4 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PoseidonT4__factory {
    return super.connect(runner) as PoseidonT4__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonT4Interface {
    return new Interface(_abi) as PoseidonT4Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): PoseidonT4 {
    return new Contract(address, _abi, runner) as unknown as PoseidonT4;
  }
}
